openapi: 3.0.0
info:
  title: Todo-app
  description: Todo-app app API
  version: 0.1.9

servers:
  - url: http://todo-app-api-production-2c38.up.railway.app/api/todos
    description: production server
  - url: http://localhost:3000/api
    description: local server

paths:
  /todos:
    get:
      tags:
        - Todos
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
